import { parseTable } from "./parse.ts";
import rawData from "./portfolio.json";
import type {
  AccountRow, AnalystRating, CryptoPrice, LegacyTx, MacroEvent, NewsHeadline,
  OptionRisk, PortfolioData, PortfolioEvent, Position, PriceRow, Quote, SecFiling,
  SourceStatus,
} from "../types.ts";

interface RawData {
  meta: { date: string; source: string };
  accounts: string;
  positions: string;
  quotes: string;
  prices: string;
  legacyTransactions: string;
  optionRisk: string;
  events?: string;
  sourceStatus?: string;
  secFilings?: string;
  macroEvents?: string;
  cryptoPrices?: string;
  analystRatings?: string;
  newsHeadlines?: string;
}

function normalizeLegacy(rows: LegacyTx[]): LegacyTx[] {
  // The legacy CSV names the ticker column `underlying`; ensure both symbol and
  // underlying are populated for lookups.
  return rows.map((r) => ({
    ...r,
    underlying: r.underlying || r.symbol || "",
    trade_date: (r.trade_date || "").slice(0, 10),
  }));
}

/**
 * Build the typed model from the data bundled at build time
 * (src/data/portfolio.json, regenerated by scripts/dataToJson.mjs). Importing
 * rather than fetching is what lets the single-file build open from file://.
 */
export function loadPortfolio(): PortfolioData {
  const raw = rawData as RawData;
  return {
    meta: raw.meta,
    accounts: parseTable<AccountRow>(raw.accounts),
    positions: parseTable<Position>(raw.positions),
    quotes: parseTable<Quote>(raw.quotes),
    prices: parseTable<PriceRow>(raw.prices),
    legacyTransactions: normalizeLegacy(parseTable<LegacyTx>(raw.legacyTransactions)),
    optionRisk: parseTable<OptionRisk>(raw.optionRisk),
    events: parseTable<PortfolioEvent>(raw.events),
    sourceStatus: parseTable<SourceStatus>(raw.sourceStatus),
    secFilings: parseTable<SecFiling>(raw.secFilings),
    macroEvents: parseTable<MacroEvent>(raw.macroEvents),
    cryptoPrices: parseTable<CryptoPrice>(raw.cryptoPrices),
    analystRatings: parseTable<AnalystRating>(raw.analystRatings),
    newsHeadlines: parseTable<NewsHeadline>(raw.newsHeadlines),
  };
}
