INSERT INTO occurrences VALUES(93,3,0,'word','飛行機','飛行機');
INSERT INTO occurrences VALUES(94,3,0,'word','乗る','乗る');
INSERT INTO occurrences VALUES(95,3,0,'word','予定','予定');
INSERT INTO occurrences VALUES(96,3,0,'grammar','g_ru_koto_ni_naru','Verb る 予定です');
INSERT INTO occurrences VALUES(97,4,0,'word','猫','猫');
INSERT INTO occurrences VALUES(98,4,0,'word','好き','好き');
INSERT INTO occurrences VALUES(99,4,0,'grammar','g_a_wa_b_ga','A は B が〜');
INSERT INTO occurrences VALUES(100,5,0,'word','台風','台風');
INSERT INTO occurrences VALUES(101,5,0,'word','6号','6号');
INSERT INTO occurrences VALUES(102,5,0,'word','ニュース','ニュース');
INSERT INTO occurrences VALUES(103,5,0,'grammar','g_noun_wa','Noun は～');
INSERT INTO occurrences VALUES(104,5,1,'word','気象庁','気象庁');
INSERT INTO occurrences VALUES(105,5,1,'word','台風','台風');
INSERT INTO occurrences VALUES(106,5,1,'word','沖縄','沖縄');
INSERT INTO occurrences VALUES(107,5,1,'word','近く','近く');
INSERT INTO occurrences VALUES(108,5,1,'word','北','北');
INSERT INTO occurrences VALUES(109,5,1,'word','進む','進んで');
INSERT INTO occurrences VALUES(110,5,1,'grammar','g_ni_yoreba','～によれば');
INSERT INTO occurrences VALUES(111,5,1,'grammar','g_verb_te_imasu','Verb て います');
INSERT INTO occurrences VALUES(112,5,2,'word','沖縄','沖縄');
INSERT INTO occurrences VALUES(113,5,2,'word','奄美','奄美');
INSERT INTO occurrences VALUES(114,5,2,'word','強い','強い');
INSERT INTO occurrences VALUES(115,5,2,'word','風','風');
INSERT INTO occurrences VALUES(116,5,2,'word','吹く','吹いて');
INSERT INTO occurrences VALUES(117,5,2,'grammar','g_noun_ya_noun_nado','Noun や Noun など～');
INSERT INTO occurrences VALUES(118,5,2,'grammar','g_verb_te_imasu','Verb て います');
INSERT INTO occurrences VALUES(119,5,3,'word','走る','走って');
INSERT INTO occurrences VALUES(120,5,3,'word','トラック','トラック');
INSERT INTO occurrences VALUES(121,5,3,'word','倒れる','倒れる');
INSERT INTO occurrences VALUES(122,5,3,'word','強い','強い');
INSERT INTO occurrences VALUES(123,5,3,'word','風','風');
INSERT INTO occurrences VALUES(124,5,3,'word','吹く','吹く');
INSERT INTO occurrences VALUES(125,5,3,'grammar','g_verb_te_imasu','Verb て います');
INSERT INTO occurrences VALUES(126,5,3,'grammar','g_kurai','～くらい～');
INSERT INTO occurrences VALUES(127,5,3,'grammar','g_kamoshirenai','～かもしれない');
INSERT INTO occurrences VALUES(128,5,4,'word','雨','雨');
INSERT INTO occurrences VALUES(129,5,4,'word','降る','降って');
INSERT INTO occurrences VALUES(130,5,4,'word','山','山');
INSERT INTO occurrences VALUES(131,5,4,'word','崩れる','崩れ');
INSERT INTO occurrences VALUES(132,5,4,'word','川','川');
INSERT INTO occurrences VALUES(133,5,4,'word','水','水');
INSERT INTO occurrences VALUES(134,5,4,'word','あふれる','あふれ');
INSERT INTO occurrences VALUES(135,5,4,'word','心配','心配');
INSERT INTO occurrences VALUES(136,5,4,'grammar','g_tari_tari_shimasu','～たり、～たり します');
INSERT INTO occurrences VALUES(137,5,4,'grammar','g_arimasu','～あります');
INSERT INTO occurrences VALUES(138,5,5,'word','台風','台風');
INSERT INTO occurrences VALUES(139,5,5,'word','2日','2日');
INSERT INTO occurrences VALUES(140,5,5,'word','3日','3日');
INSERT INTO occurrences VALUES(141,5,5,'word','西日本','西日本');
INSERT INTO occurrences VALUES(142,5,5,'word','東日本','東日本');
INSERT INTO occurrences VALUES(143,5,5,'word','近く','近く');
INSERT INTO occurrences VALUES(144,5,5,'word','来る','来');
INSERT INTO occurrences VALUES(145,5,5,'grammar','g_noun_to','Noun と～');
INSERT INTO occurrences VALUES(146,5,5,'grammar','g_sou_da','～そうだ');
INSERT INTO occurrences VALUES(147,5,6,'word','台風','台風');
INSERT INTO occurrences VALUES(148,5,6,'word','新しい','新しい');
INSERT INTO occurrences VALUES(149,5,6,'word','情報','情報');
INSERT INTO occurrences VALUES(150,5,6,'word','調べる','調べて');
INSERT INTO occurrences VALUES(151,5,6,'word','近く','近く');
INSERT INTO occurrences VALUES(152,5,6,'word','来る','来る');
INSERT INTO occurrences VALUES(153,5,6,'word','準備','準備');
INSERT INTO occurrences VALUES(154,5,6,'grammar','g_verb_te','Verb て～');
INSERT INTO occurrences VALUES(155,5,6,'grammar','g_ru_mae_ni','Verb る 前に');
INSERT INTO occurrences VALUES(156,5,6,'grammar','g_verb_te_kudasai','Verb て ください');
INSERT INTO occurrences VALUES(157,5,7,'word','飛行機','飛行機');
INSERT INTO occurrences VALUES(158,5,7,'word','新幹線','新幹線');
INSERT INTO occurrences VALUES(159,5,7,'word','乗る','乗る');
INSERT INTO occurrences VALUES(160,5,7,'word','予定','予定');
INSERT INTO occurrences VALUES(161,5,7,'word','人','人');
INSERT INTO occurrences VALUES(162,5,7,'word','情報','情報');
INSERT INTO occurrences VALUES(163,5,7,'word','調べる','調べ');
INSERT INTO occurrences VALUES(164,5,7,'grammar','g_noun_ya_noun_nado','Noun や Noun など～');
INSERT INTO occurrences VALUES(165,5,7,'grammar','g_tsumori','Verb つもり');
INSERT INTO occurrences VALUES(166,5,7,'grammar','g_mashou','Verb ましょう');
INSERT INTO occurrences VALUES(167,6,0,'word','現在','現在');
INSERT INTO occurrences VALUES(168,6,0,'word','緊急','緊急');
INSERT INTO occurrences VALUES(169,6,0,'word','災害','災害');
INSERT INTO occurrences VALUES(170,6,0,'word','用','用');
INSERT INTO occurrences VALUES(171,6,0,'word','軽量化','軽量化');
INSERT INTO occurrences VALUES(172,6,0,'word','ページ','ページ');
INSERT INTO occurrences VALUES(173,6,0,'word','表示','表示');
INSERT INTO occurrences VALUES(174,6,0,'word','する','し');
INSERT INTO occurrences VALUES(175,6,0,'grammar','g_verb_te_imasu','Verb て います');
INSERT INTO occurrences VALUES(176,6,0,'grammar','g_tame_ni','Verb ために');
INSERT INTO occurrences VALUES(177,6,1,'word','バッテリー','バッテリー');
INSERT INTO occurrences VALUES(178,6,1,'word','節約','節約');
INSERT INTO occurrences VALUES(179,6,1,'word','なる','なり');
INSERT INTO occurrences VALUES(180,6,1,'grammar','g_noun_ni_narimasu','Noun に なります');
INSERT INTO occurrences VALUES(181,6,1,'grammar','g_noun_mo','Noun も〜');
INSERT INTO occurrences VALUES(182,7,0,'word','アメリカ','アメリカ');
INSERT INTO occurrences VALUES(183,7,0,'word','イラン','イラン');
INSERT INTO occurrences VALUES(184,7,0,'word','戦い','戦い');
INSERT INTO occurrences VALUES(185,7,0,'word','続く','続い');
INSERT INTO occurrences VALUES(186,7,0,'word','いろいろ','いろいろ');
INSERT INTO occurrences VALUES(187,7,0,'word','物','物');
INSERT INTO occurrences VALUES(188,7,0,'word','値段','値段');
INSERT INTO occurrences VALUES(189,7,0,'word','上がる','上がっ');
INSERT INTO occurrences VALUES(190,7,0,'grammar','g_noun_ya_noun_nado','Noun など');
INSERT INTO occurrences VALUES(191,7,0,'grammar','g_verb_te','Verb て');
INSERT INTO occurrences VALUES(192,7,0,'grammar','g_verb_te_imasu','Verb ています');
INSERT INTO occurrences VALUES(193,7,1,'word','国会','国会');
INSERT INTO occurrences VALUES(194,7,1,'word','5日','5日');
INSERT INTO occurrences VALUES(195,7,1,'word','国','国');
INSERT INTO occurrences VALUES(196,7,1,'word','予算','予算');
INSERT INTO occurrences VALUES(197,7,1,'word','3兆1000億円','3兆1000億円');
INSERT INTO occurrences VALUES(198,7,1,'word','増やす','増やす');
INSERT INTO occurrences VALUES(199,7,1,'word','決める','決め');
INSERT INTO occurrences VALUES(200,7,1,'grammar','g_noun_gurai','Noun ぐらい');
INSERT INTO occurrences VALUES(201,7,1,'grammar','g_ru_koto','Verb ること');
INSERT INTO occurrences VALUES(202,7,2,'word','政府','政府');
INSERT INTO occurrences VALUES(203,7,2,'word','お金','お金');
INSERT INTO occurrences VALUES(204,7,2,'word','使う','使っ');
INSERT INTO occurrences VALUES(205,7,2,'word','経済','経済');
INSERT INTO occurrences VALUES(206,7,2,'word','悪い','悪く');
INSERT INTO occurrences VALUES(207,7,2,'word','なる','なら');
INSERT INTO occurrences VALUES(208,7,2,'word','する','し');
INSERT INTO occurrences VALUES(209,7,2,'word','考える','考え');
INSERT INTO occurrences VALUES(210,7,2,'grammar','g_verb_te','Verb て');
INSERT INTO occurrences VALUES(211,7,2,'grammar','g_i_adjective_ku_verb','い-Adjective く + Verb');
INSERT INTO occurrences VALUES(212,7,2,'grammar','g_you_ni_n4','Verb ようにする');
INSERT INTO occurrences VALUES(213,7,2,'grammar','g_to_omou','～と考えています');
INSERT INTO occurrences VALUES(214,7,3,'word','電気代','電気代');
INSERT INTO occurrences VALUES(215,7,3,'word','ガス代','ガス代');
INSERT INTO occurrences VALUES(216,7,3,'word','安い','安く');
INSERT INTO occurrences VALUES(217,7,3,'word','できる','でき');
INSERT INTO occurrences VALUES(218,7,3,'word','準備','準備');
INSERT INTO occurrences VALUES(219,7,3,'grammar','g_noun_ya_noun_nado','Noun や Noun など');
INSERT INTO occurrences VALUES(220,7,3,'grammar','g_i_adjective_ku_verb','い-Adjective く + Verb');
INSERT INTO occurrences VALUES(221,7,3,'grammar','g_you_ni_n4','Verb ように');
INSERT INTO occurrences VALUES(222,7,3,'grammar','g_verb_te_imasu','Verb ています');
INSERT INTO occurrences VALUES(223,7,4,'word','政府','政府');
INSERT INTO occurrences VALUES(224,7,4,'word','予算','予算');
INSERT INTO occurrences VALUES(225,7,4,'word','国債','国債');
INSERT INTO occurrences VALUES(226,7,4,'word','出す','出し');
INSERT INTO occurrences VALUES(227,7,4,'word','お金','お金');
INSERT INTO occurrences VALUES(228,7,4,'word','借りる','借りる');
INSERT INTO occurrences VALUES(229,7,4,'word','予定','予定');
INSERT INTO occurrences VALUES(230,7,4,'grammar','g_tame_ni','Noun のために');
INSERT INTO occurrences VALUES(231,7,4,'grammar','g_verb_te','Verb て');
INSERT INTO occurrences VALUES(232,7,4,'grammar','g_tsumori','Verb 予定です');
